"use client";

import Link from "next/link";
import { ArrowRight, Flask, GraduationCap } from "@phosphor-icons/react";
import { motion, useReducedMotion } from "motion/react";
import { useEffect, useMemo, useState } from "react";
import { BlockDiagram } from "./BlockDiagram";
import { defaultPID } from "@/lib/pid";
import { defaultPlant } from "@/lib/plants";
import { defaultEffects, defaultSimulation, simulate } from "@/lib/simulation";
import type { PIDConfig } from "@/lib/types";

const gainMeta = [
  { key: "kp", symbol: "P", label: "present error", min: 0, max: 5, step: .01, color: "p" },
  { key: "ki", symbol: "I", label: "error memory", min: 0, max: 2, step: .01, color: "i" },
  { key: "kd", symbol: "D", label: "rate of change", min: 0, max: 1, step: .005, color: "d" },
] as const;

export function HeroExperiment() {
  const reduced = useReducedMotion();
  const [pid, setPid] = useState<PIDConfig>({ ...defaultPID, kp: 1.25, ki: .42, kd: .08, outputMin: -2, outputMax: 2 });
  const [cursor, setCursor] = useState(0);
  const result = useMemo(() => simulate(pid, { ...defaultPlant, kind: "fopdt", gain: 1, tau: 1.7, deadTime: .16 }, defaultEffects, { ...defaultSimulation, duration: 9, dt: .02 }), [pid]);
  const samples = result.samples;

  useEffect(() => {
    if (reduced || !samples.length) return;
    let frame = 0;
    const started = performance.now();
    const tick = (now: number) => {
      const seconds = ((now - started) / 1000) % 9;
      setCursor(Math.min(samples.length - 1, Math.floor(seconds / .02)));
      frame = requestAnimationFrame(tick);
    };
    frame = requestAnimationFrame(tick);
    return () => cancelAnimationFrame(frame);
  }, [reduced, samples.length]);

  const sample = samples[Math.min(cursor, samples.length - 1)] ?? samples[0];
  const visible = samples.filter((_, index) => index % 7 === 0);
  const path = visible.map((point, index) => {
    const x = (index / Math.max(1, visible.length - 1)) * 1000;
    const y = 180 - Math.max(-.25, Math.min(1.35, point.pv)) * 105;
    return `${index ? "L" : "M"}${x.toFixed(1)},${y.toFixed(1)}`;
  }).join(" ");
  const currentX = sample ? (sample.t / 9) * 1000 : 0;

  return (
    <section className="hero hero-instrument section-pad" aria-label="Live PID experiment">
      <div className="eyebrow"><span>OPEN CONTROL LAB / LIVE MODEL</span><span>FOPDT · RK4 · PIDF</span></div>
      <div className="hero-instrument-grid">
        <motion.div className="hero-copy-column" initial={reduced ? false : { opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .5 }}>
          <p className="hero-index">INPUT → RESPONSE → FEEDBACK → UNDERSTANDING</p>
          <h1>PID <span>LOOP</span> LAB</h1>
          <p className="hero-subtitle">Interactive PID Tuning &amp; Control-System Simulator</p>
          <p className="hero-directive">Change the controller.<br />Watch the loop respond.</p>
          <div className="hero-actions">
            <Link className="button primary" href="/lab"><Flask aria-hidden="true" />Enter lab<ArrowRight aria-hidden="true" /></Link>
            <Link className="button" href="/learn"><GraduationCap aria-hidden="true" />Learn PID</Link>
          </div>
        </motion.div>

        <div className="hero-scope" aria-label="Live closed-loop process response generated by the simulation engine">
          <div className="scope-label"><span>LIVE RESPONSE / y(t)</span><strong>{sample?.t.toFixed(2) ?? "0.00"} s</strong></div>
          <svg viewBox="0 0 1000 210" role="img" aria-label="Simulated process value tracking a unit setpoint">
            <defs><pattern id="hero-grid" width="50" height="35" patternUnits="userSpaceOnUse"><path d="M 50 0 L 0 0 0 35" /></pattern></defs>
            <rect width="1000" height="210" fill="url(#hero-grid)" />
            <path className="hero-setpoint-line" d="M0,75 L1000,75" />
            <path className="hero-response-line" d={path} />
            <line className="hero-time-line" x1={currentX} x2={currentX} y1="16" y2="196" />
            <circle className="hero-time-point" cx={currentX} cy={180 - Math.max(-.25, Math.min(1.35, sample?.pv ?? 0)) * 105} r="5" />
          </svg>
          <div className="hero-telemetry" aria-live="polite">
            {[["SP", sample?.setpoint], ["PV", sample?.pv], ["ERROR", sample?.error], ["OUTPUT", sample?.output]].map(([label, value]) => <span key={label as string}><small>{label}</small><strong>{Number(value ?? 0).toFixed(3)}</strong></span>)}
          </div>
        </div>
      </div>

      <div className="hero-controller">
        <div className="hero-gains">
          {gainMeta.map((gain) => (
            <label className={`hero-gain ${gain.color}`} key={gain.key}>
              <span className="gain-symbol">{gain.symbol}</span>
              <span className="gain-copy"><strong>K{gain.symbol.toLowerCase()} <output>{pid[gain.key].toFixed(3)}</output></strong><small>{gain.label}</small></span>
              <input type="range" aria-label={`${gain.symbol} gain`} min={gain.min} max={gain.max} step={gain.step} value={pid[gain.key]} onChange={(event) => setPid((current) => ({ ...current, [gain.key]: Number(event.target.value) }))} />
            </label>
          ))}
        </div>
        <div className="hero-equation-live" aria-label="Live PID contribution decomposition">
          <span className="eq-p"><b>{sample?.p.toFixed(3) ?? "0.000"}</b><small>Kp e(t)</small></span><i>+</i>
          <span className="eq-i"><b>{sample?.i.toFixed(3) ?? "0.000"}</b><small>Ki ∫ e(t)dt</small></span><i>+</i>
          <span className="eq-d"><b>{sample?.d.toFixed(3) ?? "0.000"}</b><small>Kd de(t)/dt</small></span><i>=</i>
          <span className="eq-u"><b>{sample?.unclamped.toFixed(3) ?? "0.000"}</b><small>u(t)</small></span>
        </div>
      </div>
      <BlockDiagram sample={sample} />
      <p className="hero-proof">Every trace and value above comes from the same deterministic simulation engine used in the laboratory.</p>
    </section>
  );
}
